export const MAKE_URLS_SUCCESS = 'MAKE_URLS_SUCCESS';
export const MAKE_URLS_FAILURE = 'MAKE_URLS_FAILURE';
export const URL_ITEM_CLICKED = 'URL_ITEM_CLICKED';
export const FETCH_URL_DETAILS_SUCCESS = 'FETCH_URLS_DETAILS_SUCCESS';
export const FETCH_URL_DETAILS_FAILURE = 'FETCH_URLS_DETAILS_FAILURE';
export const URL_REDIRECTION_SUCCESS = 'URL_REDIRECTION_SUCCESS';
export const URL_REDIRECTION_FAILURE = 'URL_REDIRECTION_FAILURE';



export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

export const FETCH_USER_URLS_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_URLS_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';



export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CLEAR_DATA = 'CLEAR_DATA';
export const LOGOUT = 'LOGOUT';
